name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (number only)'
        required: true
        type: number

permissions:
  contents: write

jobs:
  build:
    name: Build binaries
    runs-on: windows-2022
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - If LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-architecture: x64
          vs-prerelease: true

      - name: Generate project files (premake)
        run: premake/premake5 vs2022 --ci-build

      - name: Compile
        id: compile
        run: msbuild /m /v:minimal /p:Configuration=Release /p:Platform=Win32 build/Fuck_off_EA_App.sln

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            build/bin/Win32-Release/version.dll
            build/bin/Win32-Release/version.pdb

      - name: Create innosetup install package
        run: iscc .\setup.iss /DMyAppVersion=${{ inputs.version || github.sha }}
      - name: Upload setup as artifact
        uses: actions/upload-artifact@v3
        with:
          name: installer
          path: Fuck_off_EA_App_installer.exe

      - name: Create release
        if: github.ref == 'refs/heads/master' && steps.compile.conclusion == 'success' && github.event_name == 'workflow_dispatch'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.version }}
          name: Release v${{ inputs.version }}
          #body: ${{ github.event.inputs.changelog }}
          body: Auto-generated release version for build `${{ github.sha }}`
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            Fuck_off_EA_App_installer.exe
            build/bin/Win32-Release/version.dll
